name: CI Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  

jobs:
  test_backend:
    name: Test Backend Code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' 

    - name: Install backend dependencies
      run: pip install -r backend/requirements.txt

    - name: Run Django tests
      run: python backend/manage.py test
      
      

  build_and_push_backend:
    name: Build and Push Backend Image to Docker Hub
    runs-on: ubuntu-latest
    needs: test_backend
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push backend Docker image to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/foodgram-backend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/foodgram-backend:${{ github.sha }}

  build_and_push_frontend:
    name: Build and Push Frontend Image to Docker Hub
    runs-on: ubuntu-latest
    needs: test_backend
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push frontend Docker image to Docker Hub
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/foodgram-frontend:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/foodgram-frontend:${{ github.sha }}

        
